### ISSUE TITLE
.APK Download

### ISSUE THREAD

**Issue by harroguk** [gorillamoe/Unofficial-Fitocracy.com-Android-App#1]
Any chance you can please put a compiled version here for us non-programmer types to download?

Thanks

**Comment by gorillamoe** [comment]
I would love to do that and continue development. If we can get Brian Wang to "officially" allow us to use the private API. I don't need documentation for that. :) I'll leave this open until Brian replies :)

If we are allowed to use the API, I will also put a forvever free, never ever paid-version in the playstore :)
